/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// 음료 메뉴 아이템 타입 정의
export interface BeverageItem {
  id: string;
  name: string;
  price: number;
}

// 사이즈 옵션 타입 정의
export interface SizeOption {
  id: 'S' | 'M' | 'L';
  name: string;
  extraPrice: number;
}

// 추가 옵션 타입 정의
export interface ExtraOption {
  id: string;
  name: string;
  price: number;
}

// 주문서 폼 상태 인터페이스
export interface OrderFormData {
  customerName: string;      // 1. 주문자 이름 (필수)
  phoneNumber: string;       // 2. 전화번호
  beverageId: string;        // 3. 선택된 음료 ID
  size: 'S' | 'M' | 'L';     // 4. 사이즈 (기본값 M)
  extraOptionIds: string[];  // 5. 선택된 추가 옵션 ID 목록
  quantity: number;          // 6. 주문 수량 (기본값 1, 1~10)
  requests: string;          // 7. 요청사항
}

// 접수된 주문 기록 인터페이스
export interface OrderRecord {
  id: string;
  customerName: string;
  phoneNumber: string;
  beverageName: string;
  sizeName: string;
  extraOptionsSummary: string;
  quantity: number;
  requests: string;
  totalPrice: number;
  confirmationMessage: string;
  orderedAt: string;
}

// 음료 기본 메뉴 목록 (프롬프트 요구사항 반영)
export const BEVERAGE_MENU: BeverageItem[] = [
  { id: 'americano', name: '아메리카노', price: 3500 },
  { id: 'caffe_latte', name: '카페라떼', price: 4000 },
  { id: 'caffe_mocha', name: '카페모카', price: 4500 },
  { id: 'vanilla_latte', name: '바닐라라떼', price: 4500 },
  { id: 'greentea_latte', name: '녹차라떼', price: 4500 },
];

// 사이즈 선택 목록 (프롬프트 요구사항: S +0원, M +500원(기본), L +1,000원)
export const SIZE_OPTIONS: SizeOption[] = [
  { id: 'S', name: 'S', extraPrice: 0 },
  { id: 'M', name: 'M', extraPrice: 500 },
  { id: 'L', name: 'L', extraPrice: 1000 },
];

// 추가 옵션 목록 (프롬프트 요구사항 반영)
export const EXTRA_OPTIONS: ExtraOption[] = [
  { id: 'shot', name: '샷 추가', price: 500 },
  { id: 'cream', name: '크림 추가', price: 500 },
  { id: 'syrup', name: '시럽 추가', price: 300 },
  { id: 'decaf', name: '디카페인', price: 0 },
];

// Supabase SQL Editor에 복사할 테이블 및 정책 설정
export const SUPABASE_SQL_SCRIPT = `
CREATE TABLE IF NOT EXISTS public.cafe_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(100) NOT NULL,
  phone_number VARCHAR(30),
  beverage_name VARCHAR(100) NOT NULL,
  size_option VARCHAR(10) NOT NULL DEFAULT 'M',
  extra_options TEXT[] NOT NULL DEFAULT '{}',
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity BETWEEN 1 AND 10),
  requests TEXT,
  total_price INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.cafe_menu ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, DELETE ON public.cafe_menu TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.cafe_menu_id_seq TO anon, authenticated;

DROP POLICY IF EXISTS "Public can read cafe orders" ON public.cafe_menu;
CREATE POLICY "Public can read cafe orders"
  ON public.cafe_menu FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Public can create cafe orders" ON public.cafe_menu;
CREATE POLICY "Public can create cafe orders"
  ON public.cafe_menu FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Public can clear cafe orders" ON public.cafe_menu;
CREATE POLICY "Public can clear cafe orders"
  ON public.cafe_menu FOR DELETE TO anon, authenticated USING (true);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'cafe_menu'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.cafe_menu;
  END IF;
END $$;
`;
